### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by holdenk** [sparklingpandas/sparklingpandas#123]
We have some very high quality print debugging, which would be better suited to a logging mechanism.

**Comment by dgtall** [comment]
Hello, 
let me know if I can help in adding logging. If you can help me with some tips or pointers I would like to contribute to basic tasks like this so that I will also be able to understand the functionality.
Thanks

**Comment by jhlch** [comment]
Hi,
Thanks for your interesting in contributing. A good python logging tutorial [can be found here.](https://docs.python.org/2/howto/logging.html) The basic gist of this ticket is that we have 12 print statements in our python code, and 11* of them should actually be log statements. Printing to the shell works when we are running locally, but if we were to deploy a sparkling pandas application on a cluster, our print statements would likely get lost out on a machine somewhere unless we were very very careful about capturing stdout. If we log instead of print, users will have an easier time seeing our debug, error, and warning messages no matter how they deploy their application.

If you convert print statements to the most appropriate log statement (ie debug, info, error, or warn) I would be happy to review your patch with you. Let me know if you have more questions or need anything.

*The one that should be left as a print statement is in shell.py. Printing information to the shell, in our own shell is exactly what we want there.

**Comment by jhlch** [comment]
Fixed in 76fc662a30d5d79ad71d972ba7946140b83a6c4a
